spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/k9?currentSchema=security
    password: k9
    username: k9
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create

